import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
import Navigation from "../components/navigation";
import Search from "../components/search-container";
import TrendingList from "../components/ui-components/trendingList";
import MovieList from "../components/ui-components/movie-list";
import { useContext } from "react";
import { dataContext } from "../context/dataContext";

export default function Home() {
  const { allMovies: data } = useContext(dataContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />

      <main className="main-content">
        <Search title={"Search for movies or TV series"} />
        <TrendingList />
        <div className="grid-container">
          <h1 className="title">Recommended for you</h1>

          <MovieList data={data} />
        </div>
      </main>
    </>
  );
}
